name: HelloWorld

on:
  push:
    branches: [ "main" ]

    
jobs:
  usingUbuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print Hello, world
      run: echo "Hello, world"

  usingWindows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print Hello, world
      run: echo "Hello, world"
  

  usingMacOS:
    runs-on: macos-latest

    steps:
   - uses: actions/checkout@v3
    - name: Print Hello, world
      run: echo "Hello, world"